 /* Fri Feb  8 20:09:56 CST 2019
 * This is going to be a tool I can use with the csv files generated by The Wahoo Fitness app.
 * It will:
 *     ✓ strip the speed values in mps from the csv file,
 *     ✓ calculate AP
 *     ✓ calculate NP
 *     ✓ calculate FTP
 *     ✓ calculate IF
 *     ✓ calculate TSS
 *     * log the tss and ftp values in a db sorted by date
 * For those values in db, it will:
 *     * calculate CTL (fitness)
 *     * calculate ATL (fatigue)
 *     * calculate TSB (freshness)
 *
 * Those values will be kept in db. db is basically a spreadsheet.
 *
 * If I can display a graph of both the first set of values calculated for the
 * ride, and the values in the db, then that would be pretty sweet too.
 *
 * After that, it should be able to learn when my freshness is at a point where I
 * need to minimise my TSS.  However, it needs to also recommend how much tss I
 * can handle on the current day. If a TSS value would push my freshness too low,
 * then it will recommend a lower value. If freshness is already too low, it will
 * recommend a day off. It won't allow my fitness to drop though. The whole point
 * is that it will maximise progress while avoiding burnout.
 *
 * One more thing: I need it to see new csv files that appear in a certain
 * folder in Dropbox and automatically process them when they are found.
 *
 * I think this might be a job for sql, but for now I'm going to do it the ugly way.
 *
 * Some of the above tasks are done. I need to make the code not completely fail when the numbers get massive.
 * Then, clean up the code. Also, sort FTp so it works with workouts less than 20 mins. and shit like that.
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

int rolling_average(double* array, double* target, unsigned n, unsigned interval);

int main(int argc, char** argv){
    double *mps;                // dynamic array to hold mps values from csv file.
    double *np_ra;              // dynamic array to calculate rolling averages.
    double AP;                  // average power.
    double NP;                  // normalised power.
    double FTP;                 // functional threshold power.
    double IF;                  // intensity factor.
    double TSS;                 // training stress score.
    char c;
    FILE *csv, *log;            // wahoo csv file for input, log for output.
    unsigned i, j, n = 0;
    time_t timestamp;           // unix timestamp from wahoo file.
    long long llv;              // Need to read timestamp.

    if(argc != 2){
        puts("I need one argument on command line.");
        exit(1);
    }

    // Open the Wahoo Fitness csv file.
    if((csv = fopen(argv[1],"r")) == NULL){ printf("\ncan't open \'%s\'.", argv[1]); exit(1); }

    // Counts lines in the file. This is ugly. Assumes file
    // doesn't end with newline and has at least one line.
    while((c = fgetc(csv)) != EOF) if(c == '\n') n++;
    rewind(csv);

    // malloc space for n mps values.
    if((mps = malloc(n * sizeof(double))) == NULL){ puts("\nmalloc failed."); exit(1); }

    // malloc space for n NP values.
    if((np_ra = malloc(n * sizeof(double))) == NULL){ puts("\nmalloc failed."); exit(1); }

    // Read just the mps values into the array.
    // Skip header line.
    while((c = fgetc(csv)) != '\n' && c != EOF);

    // Grab the first timestamp while I'm here.
    fscanf(csv,"%lld", &llv);
    timestamp = llv;

    // Skip the first 6 fields and read the 7th.
    unsigned comma = i = 0;
    while((c = fgetc(csv)) != EOF){

        // Skip first 6 fields.
        while(comma < 6){
            c = fgetc(csv);
            if(c == ',')
                comma++;
        }
        // Read the float in the 7th field.
        fscanf(csv, "%lf", &mps[i++]);

        // skip to the next line.
        while((c = fgetc(csv)) != '\n' && c != EOF);
        comma = 0;
    }

    fclose(csv);

    // calculate AP.
    AP = 0.0;
    for(i = 0; i < n; i++){

        // convert mps to mph.
        mps[i] *= 2.23694;

        // convert to watts using Kinetic's formula.
        mps[i] = 5.24482 * mps[i] + 0.01968 * mps[i] * mps[i] * mps[i];

        // calculate average power.
        AP += mps[i] / (double)n;
    }

    // Calculate 30-sec rolling average for NP.
    rolling_average(mps, np_ra, n, 30);

    // Raise each value to 4th power and calc average.
    NP = 0.0;
    for(i = 0; i < n; i++){
        np_ra[i] = np_ra[i] * np_ra[i] * np_ra[i] * np_ra[i];
        NP += np_ra[i] / (double)n;
    }

    // Find 4th root of this number.
    NP = sqrt(sqrt(NP));

    // Calculate FTP: maximum value from 20-min rolling average.
    rolling_average(mps, np_ra, n, 1200);
    FTP = 0;
    for(i = 0; i < n; i++){
        if(np_ra[i] > FTP)
            FTP = np_ra[i];
    }
    FTP *= 0.95;   // This number is actually bullshit if the workout is less than 20 minutes. Fix later.

    // Calc IF.
    IF = NP / FTP;

    // Calc TSS.
    TSS = IF * IF * 100.0 * ((double)n / 3600.0);

    // Display all the things.
    printf("%u sec workout (%u mins).\n", n, n / 60);
    printf("AP = %lf\nNP = %lf\nFTP = %lf\nIF = %lf\nTSS = %lf\n", AP, NP, FTP, IF, TSS);

    // write date, ftp and tss to log.
    if((log = fopen("tss.log","a")) == NULL){ puts("can't open tss.log\n"); exit(1); }
    fprintf(log, "%lld,%lf,%lf\n", (long long)timestamp, FTP, TSS);
    fclose(log);
}



int rolling_average(double* array, double* target, unsigned n, unsigned interval){
    for(unsigned i = 0; i < n; i++){
        if(i < interval){
            if(i == 0)
                    target[i] = array[i];
            else
                target[i] = (target[i - 1] * i + array[i]) / (i + 1);
        }
        else
            target[i] = (target[i - 1] * interval + array[i] - array[i - interval]) / interval;
    }
}
