 /*
  * Fri Feb  8 20:09:56 CST 2019
  * This is going to be a tool I can use with the csv files generated by The Wahoo Fitness app.
  * Strips speed values from file and calculates various cycling metrics, notably TSS.
  * Then, can advise on best TSS range to aim for, given your 'freshness' threshold.
  * to compile: gcc silvercheetah.c -o silvercheetah -lm
  * usage: silvercheetah <some wahoo fitness .csv file>
  */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

int rolling_average(double* array, double* target, unsigned n, unsigned interval);

int main(int argc, char** argv){
    double *mps;                // dynamic array to hold mps values from csv file.
    double *np_ra;              // dynamic array to calculate rolling averages.
    double AP;                  // average power.
    double NP;                  // normalised power.
    double FTP;                 // functional threshold power.
    double IF;                  // intensity factor.
    double TSS;                 // training stress score.
    char c;
    FILE *csv, *log;            // wahoo csv file for input, log for output.
    unsigned i, j, n = 0;
    time_t timestamp;           // unix timestamp from wahoo file.
    long long llv;              // Need to read timestamp.

    if(argc != 2){
        printf("USAGE: %s <wahoo fitness .csv file>\n", argv[0]);
        exit(1);
    }

    // Open the Wahoo Fitness csv file.
    if((csv = fopen(argv[1],"r")) == NULL){ printf("\ncan't open \'%s\'.", argv[1]); exit(1); }

    // If you're going to check that this file is actually in the correct format, do that here.

    // Count lines in the file.
    while((c = fgetc(csv)) != EOF) if(c == '\n') n++;
    rewind(csv);

    // malloc space for n mps values.
    if((mps = malloc(n * sizeof(double))) == NULL){ fprintf(stderr, "malloc failed.\n"); exit(1); }

    // malloc space for n NP values.
    if((np_ra = malloc(n * sizeof(double))) == NULL){ fprintf(stderr, "malloc failed.\n"); exit(1); }

    // Skip header line.
    while((c = fgetc(csv)) != '\n' && c != EOF);

    // Grab the first timestamp while I'm here.
    fscanf(csv,"%lld", &llv);
    timestamp = llv;

    // Read just the mps values into the array.
    unsigned comma = i = 0;
    while((c = fgetc(csv)) != EOF){

        // Skip first 6 fields.
        while(comma < 6){
            c = fgetc(csv);
            if(c == ',')
                comma++;
        }
        // Read the float in the 7th field.
        fscanf(csv, "%lf", &mps[i++]);

        // skip to the next line.
        while((c = fgetc(csv)) != '\n' && c != EOF);

        comma = 0;
    }

    fclose(csv);

    // calculate AP.
    AP = 0.0;
    for(i = 0; i < n; i++){

        // convert mps to mph.
        mps[i] *= 2.23694;

        // convert to watts using Kinetic's formula.
        mps[i] = mps[i] * (5.24482  + 0.01968 * mps[i] * mps[i]);

        // calculate average power.
        AP += mps[i] / (double)n;
    }

    // Calculate 30-sec rolling average for NP.
    rolling_average(mps, np_ra, n, 30);

    // Raise each value to 4th power and calc average.
    NP = 0.0;
    for(i = 0; i < n; i++){
        np_ra[i] = np_ra[i] * np_ra[i] * np_ra[i] * np_ra[i];
        NP += np_ra[i] / (double)n;
    }

    // Find 4th root of this number.
    NP = sqrt(sqrt(NP));

    // Calculate FTP: maximum value from 20-min rolling average.
    rolling_average(mps, np_ra, n, 1200);
    FTP = 0.0;
    for(i = 0; i < n; i++){
        if(np_ra[i] > FTP)
            FTP = np_ra[i];
    }
    FTP *= 0.95;

    // Calc IF.
    IF = NP / FTP;

    // Calc TSS.
    TSS = IF * IF * 100.0 * ((double)n / 3600.0);

    // Display all the things.
    printf("%u sec workout (%u mins).\n", n, n / 60);
    printf("AP = %lf\nNP = %lf\nFTP = %lf\nIF = %lf\nTSS = %lf\n", AP, NP, FTP, IF, TSS);

    // Open tss.log. if it doesn't exist, create it and add a header comment to it.
    if((log = fopen("tss.log","r")) == NULL){
        if((log = fopen("tss.log","a")) == NULL){
            puts("can't create logfile.");
            exit(1);
        }
        fprintf(log, "# timestamp,FTP,TSS,CTL(fitness),ATL(fatigue),TSB(freshness)\n");
    }
    else{
        fclose(log);
        if((log = fopen("tss.log","a")) == NULL){
            puts("can't open logfile.");
            exit(1);
        }
    }
    // write timestamp, ftp and tss to log.
    fprintf(log, "%lld,%lf,%lf,,,\n", (long long)timestamp, FTP, TSS);

    fclose(log);
}



int rolling_average(double* array, double* target, unsigned n, unsigned interval){
    for(unsigned i = 0; i < n; i++){
        if(i < interval){
            if(i == 0)
                    target[i] = array[i];
            else
                target[i] = (target[i - 1] * i + array[i]) / (i + 1);
        }
        else
            target[i] = (target[i - 1] * interval + array[i] - array[i - interval]) / interval;
    }
}
